### ISSUE TITLE
Carthage + Xcode 10 : Task failed with exit code 65

### ISSUE THREAD

**Issue by abiaad** [adjust/ios_sdk#333]
Step to reproduce :

1. select xcode version by running `sudo xcode-select -switch <Path_to_Xcode10.app>`
2. Run `carthage update --platform iOS` on your project
3. Get this error : 
>Task failed with exit code 65

Did someone found a solution ?

**Comment by Igor-Palaguta** [comment]
@abiaad We faced same issue. Fix can be found here https://github.com/adjust/ios_sdk/pull/335

**Comment by uerceg** [comment]
Hey guys, thanks for reporting, will be checked this week on our side. Sorry for a bit delayed reply. Will keep you posted in here on progress.

**Comment by uerceg** [comment]
@abiaad 

Which OSX version you are using? I just got error 65 on OSX 10.14 beta when I simply attempted to upgrade Carhage, not even trying to update anything in my app project:

```
➜  ~ sudo xcode-select --switch /Applications/Xcode\ Beta.app/Contents/Developer
➜  ~ brew upgrade carthage
==> Upgrading 1 outdated package, with result:
carthage 0.27.0 -> 0.29.0
==> Upgrading carthage
==> Cloning https://github.com/Carthage/Carthage.git
Cloning into '/Users/uerceg/Library/Caches/Homebrew/carthage--git'...
remote: Counting objects: 20839, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 20839 (delta 12), reused 11 (delta 5), pack-reused 20808
Receiving objects: 100% (20839/20839), 18.00 MiB | 5.35 MiB/s, done.
Resolving deltas: 100% (13679/13679), done.
Note: checking out 'c6952b87ce11a14cf17eccb829598c4ff538b140'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> Checking out tag 0.29.0
==> make prefix_install PREFIX=/usr/local/Cellar/carthage/0.29.0
Last 15 lines from /Users/uerceg/Library/Logs/Homebrew/carthage/01.make:
                                return updatedDependencies.flatMap { (project, version) -> OutdatedDependency? in
                                                           ^
/tmp/carthage-20180626-5208-1twr9t4/Source/CarthageKit/Project.swift:487:32: note: use 'compactMap(_:)' instead
                                return updatedDependencies.flatMap { (project, version) -> OutdatedDependency? in
                                                           ^~~~~~~
                                                           compactMap

** INSTALL FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
make: *** [installables] Error 65

Do not report this issue to Homebrew/brew or Homebrew/core!


Error: You are using macOS 10.14.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```

**Comment by abiaad** [comment]
@uerceg I'm running on macOS 10.13.5

**Comment by abiaad** [comment]
@uerceg do you have some news ? 🙂

**Comment by kaybutter** [comment]
For anyone interested, I could fix the build locally by opening the Project and removing the `Copy Bundle Resources` build phase from the target. The phase was manually copying the info.plist into the framework which should not be necessary to begin with. 🤷‍♂️

**Comment by uerceg** [comment]
Hi @kaybutter and thanks for sharing this update with us. Same thing I noticed. Seems like "feature" of Xcode 10 and new build system they introduced. We will run through our SDK code to see if Carthage target (or any other as well) is causing `Info.plist` to be copied with other bundle resources (which was for sure something we were never setting explicitly, probably just default Xcode setting at the time projects were created and which now seems to starts to be flagged with Xcode 10 build system) and update SDK to remove that copy rule.

Also @abiaad, feel free to try what @kaybutter suggested, we tried it and it should solve the issue. Let us know how did it go.

**Comment by abiaad** [comment]
@uerceg yes I will, thanks @kaybutter 👍

**Comment by Sopan** [comment]
Anyone found any solution to this problem. I have looked into @kaybutter suggestion but don't see info.plist getting copied.
Tried building my app for iOS 12 using XCode 10 in Mojave, gave me error "Module compiled with Swift 4.1.x cannot be imported in Swift 4.1.x: /CarthageModulePath".
This looks like an error where frameworks were built with earlier Xcode tools, so I did ```carthage update --platform ios``` but failed with code 65.

**Comment by kaybutter** [comment]
@Sopan It's not a problem with your project but with the Adjust project. You can usually find your local adjust project file in your `Carthage/Checkouts/ios_sdk` folder. If you open the Adjust.xcodeproj file there and remove the "Copy Bundle Resources" build phase, you should be able to build your dependencies with `carthage build --platform ios`

Obviously, that's only a temporary workaround but at least you'll be able to build your project.

**Comment by uerceg** [comment]
Update in the Adjust project will be added at later point. Xcode 10 and OSX 10.14 are still in beta and we are aware of the changes which current betas contain. We will keep our eyes on these things as official release dates are getting close and SDK will be officially updated as soon as Apple releases official versions on their side.

Anticipating potential changes in beta releases proved to be bad choice couple of times for us in the past since we saw some things that were the reason for our SDK update being changed or even removed between different beta and/or official releases. 

If it would help you, we could make a separate branch on our repo and you can aim it from Cartfile. But official changes on master will be added once we make sure that they indeed behave properly with official release of Xcode 10.

**Comment by DashlaneParis** [comment]
Hello, 
Yes, a separated Xcode-beta branch will definitely be helpful

**Comment by uerceg** [comment]
Hi @DashlaneParis 

Can you please give `xcode-10-beta` branch a shot and let us know if it works for you?

Cheers

**Comment by uerceg** [comment]
Hey guys. We have just released iOS SDK v4.14.2 update (https://github.com/adjust/ios_sdk/releases/tag/v4.14.2) where Xcode 10 beta should be supported. Will close this issue now, but feel free to reopen it or ping in here in case you have any issues or further questions.

Cheers.

**Comment by strickce** [comment]
I'm having the same error when building for macOS.  I deleted the "copy bundled resources" line
from the build ( it had no items in it anyway) but that did not fix the error.  The last part of the log file is:

...
Intermediates.noindex/ArchiveIntermediates/CocoaMQTT/IntermediateBuildFilesPath/CocoaMQTT.build/Release/CocoaMQTT.build/Objects-normal/x86_64/CocoaMQTTFrame.o -o /Users/Charlie/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/CocoaMQTT/9a55aa7721cd842ed9720979eacbc9557a65cd2d/Build/Intermediates.noindex/ArchiveIntermediates/CocoaMQTT/IntermediateBuildFilesPath/CocoaMQTT.build/Release/CocoaMQTT.build/Objects-normal/x86_64/CocoaMQTTMessage.o -o /Users/Charlie/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/CocoaMQTT/9a55aa7721cd842ed9720979eacbc9557a65cd2d/Build/Intermediates.noindex/ArchiveIntermediates/CocoaMQTT/IntermediateBuildFilesPath/CocoaMQTT.build/Release/CocoaMQTT.build/Objects-normal/x86_64/CocoaMQTTDeliver.o -o /Users/Charlie/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/CocoaMQTT/9a55aa7721cd842ed9720979eacbc9557a65cd2d/Build/Intermediates.noindex/ArchiveIntermediates/CocoaMQTT/IntermediateBuildFilesPath/CocoaMQTT.build/Release/CocoaMQTT.build/Objects-normal/x86_64/CocoaMQTTTimer.o -o /Users/Charlie/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/CocoaMQTT/9a55aa7721cd842ed9720979eacbc9557a65cd2d/Build/Intermediates.noindex/ArchiveIntermediates/CocoaMQTT/IntermediateBuildFilesPath/CocoaMQTT.build/Release/CocoaMQTT.build/Objects-normal/x86_64/CocoaMQTTLogger.o
/Users/Charlie/Desktop/mqtt/Carthage/Checkouts/CocoaMQTT/Source/CocoaMQTTDeliver.swift:39:90: error: 'default' is only available in macOS 10.10 or newer
    private var deliverQueue = DispatchQueue.init(label: "deliver.cocoamqtt.emqx", qos: .default)
                                                                                         ^
/Users/Charlie/Desktop/mqtt/Carthage/Checkouts/CocoaMQTT/Source/CocoaMQTTDeliver.swift:36:7: note: add @available attribute to enclosing class
class CocoaMQTTDeliver: NSObject {
      ^
/Users/Charlie/Desktop/mqtt/Carthage/Checkouts/CocoaMQTT/Source/CocoaMQTTTimer.swift:52:98: error: 'default' is only available in macOS 10.10 or newer
    private static let target_queue = DispatchQueue(label: "io.emqx.CocoaMQTT.TimerQueue", qos: .default, attributes: .concurrent)
                                                                                                 ^
/Users/Charlie/Desktop/mqtt/Carthage/Checkouts/CocoaMQTT/Source/CocoaMQTTTimer.swift:52:24: note: add @available attribute to enclosing static property
    private static let target_queue = DispatchQueue(label: "io.emqx.CocoaMQTT.TimerQueue", qos: .default, attributes: .concurrent)
                       ^
/Users/Charlie/Desktop/mqtt/Carthage/Checkouts/CocoaMQTT/Source/CocoaMQTTTimer.swift:16:7: note: add @available attribute to enclosing class
class CocoaMQTTTimer {
      ^

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by strickce** [comment]
I just looked at the Xcode project and found that it is building tor macOS 10.9.  I tried to change it to 10.14 but it still built for 10.9.  I don't know if this is the problem, but I suspect it is.  Any suggestions?

**Comment by strickce** [comment]
I just tried building the Xcode project itself after changing the deployment target to 10.14 and it worked.  This also fails if the deployment target is 10.9.  I cannot make the 10.14 change permanent though.  When I run the Carthage update, it always fails.

**Comment by marcocattai** [comment]
> I'm having the same error when building for macOS. I deleted the "copy bundled resources" line
> from the build ( it had no items in it anyway) but that did not fix the error. The last part of the log file is:
> 
> ...
> Intermediates.noindex/ArchiveIntermediates/CocoaMQTT/IntermediateBuildFilesPath/CocoaMQTT.build/Release/CocoaMQTT.build/Objects-normal/x86_64/CocoaMQTTFrame.o -o /Users/Charlie/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/CocoaMQTT/9a55aa7721cd842ed9720979eacbc9557a65cd2d/Build/Intermediates.noindex/ArchiveIntermediates/CocoaMQTT/IntermediateBuildFilesPath/CocoaMQTT.build/Release/CocoaMQTT.build/Objects-normal/x86_64/CocoaMQTTMessage.o -o /Users/Charlie/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/CocoaMQTT/9a55aa7721cd842ed9720979eacbc9557a65cd2d/Build/Intermediates.noindex/ArchiveIntermediates/CocoaMQTT/IntermediateBuildFilesPath/CocoaMQTT.build/Release/CocoaMQTT.build/Objects-normal/x86_64/CocoaMQTTDeliver.o -o /Users/Charlie/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/CocoaMQTT/9a55aa7721cd842ed9720979eacbc9557a65cd2d/Build/Intermediates.noindex/ArchiveIntermediates/CocoaMQTT/IntermediateBuildFilesPath/CocoaMQTT.build/Release/CocoaMQTT.build/Objects-normal/x86_64/CocoaMQTTTimer.o -o /Users/Charlie/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/CocoaMQTT/9a55aa7721cd842ed9720979eacbc9557a65cd2d/Build/Intermediates.noindex/ArchiveIntermediates/CocoaMQTT/IntermediateBuildFilesPath/CocoaMQTT.build/Release/CocoaMQTT.build/Objects-normal/x86_64/CocoaMQTTLogger.o
> /Users/Charlie/Desktop/mqtt/Carthage/Checkouts/CocoaMQTT/Source/CocoaMQTTDeliver.swift:39:90: error: 'default' is only available in macOS 10.10 or newer
> private var deliverQueue = DispatchQueue.init(label: "deliver.cocoamqtt.emqx", qos: .default)
> ^
> /Users/Charlie/Desktop/mqtt/Carthage/Checkouts/CocoaMQTT/Source/CocoaMQTTDeliver.swift:36:7: note: add @available attribute to enclosing class
> class CocoaMQTTDeliver: NSObject {
> ^
> /Users/Charlie/Desktop/mqtt/Carthage/Checkouts/CocoaMQTT/Source/CocoaMQTTTimer.swift:52:98: error: 'default' is only available in macOS 10.10 or newer
> private static let target_queue = DispatchQueue(label: "io.emqx.CocoaMQTT.TimerQueue", qos: .default, attributes: .concurrent)
> ^
> /Users/Charlie/Desktop/mqtt/Carthage/Checkouts/CocoaMQTT/Source/CocoaMQTTTimer.swift:52:24: note: add @available attribute to enclosing static property
> private static let target_queue = DispatchQueue(label: "io.emqx.CocoaMQTT.TimerQueue", qos: .default, attributes: .concurrent)
> ^
> /Users/Charlie/Desktop/mqtt/Carthage/Checkouts/CocoaMQTT/Source/CocoaMQTTTimer.swift:16:7: note: add @available attribute to enclosing class
> class CocoaMQTTTimer {
> ^
> 
> ** ARCHIVE FAILED **
> 
> The following build commands failed:
> CompileSwift normal x86_64
> CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
> (2 failures)

Same issue on Mac Catalina

**Comment by Vadivel-Muniswamy** [comment]
I have this with XCode 11.6. Please anyone help on this.

**Comment by rajscet** [comment]
i have same issue

**Comment by rajscet** [comment]
reams@dreamss-imac react-native-payments-addon-stripe % carthage update --platform ios*** Fetching stripe-ios
*** Checking out stripe-ios at "v11.1.0"
*** xcodebuild output can be found in /var/folders/_n/pl3lvntx1592y88my1zbfmd80000gn/T/carthage-xcodebuild.8SpWP7.log
*** Skipped downloading stripe-ios.framework binary due to the error:
        "Bad credentials"
*** Building scheme "StripeiOS" in Stripe.xcworkspace
Build Failed
        Task failed with exit code 65:
        /usr/bin/xcrun xcodebuild -workspace /Users/dreams/Documents/Shashank/London/node_modules/react-native-payments-addon-stripe/Carthage/Checkouts/stripe-ios/Stripe.xcworkspace -scheme StripeiOS -configuration Release -derivedDataPath /Users/dreams/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/stripe-ios/v11.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/_n/pl3lvntx1592y88my1zbfmd80000gn/T/stripe-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/dreams/Documents/Shashank/London/node_modules/react-native-payments-addon-stripe/Carthage/Checkouts/stripe-ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/_n/pl3lvntx1592y88my1zbfmd80000gn/T/carthage-xcodebuild.8SpWP7.log

**Comment by VitalikKizlov** [comment]
--no-use-binaries helps me
