### ISSUE TITLE
we update 4.15.0 version  discover this crash : ADJUtil.m line 336 +[ADJUtil writeObject:fileName:objectName:]

### ISSUE THREAD

**Issue by wangjunhua1** [adjust/ios_sdk#350]

**Comment by wangjunhua1** [comment]
Previous versions （4.14.1） did not have this crash

**Comment by uerceg** [comment]
Hi @wangjunhua1 

Thanks for reporting this. Any additional information maybe on device type and iOS version you saw this happening onto? Also, is this something you can reproduce?

**Comment by wangjunhua1** [comment]
<img width="705" alt="image" src="https://user-images.githubusercontent.com/11474284/46600414-aa362c80-cb1c-11e8-9270-f396a720b6c0.png">
All devices have this problem

**Comment by uerceg** [comment]
And how is it reproducible? Just by initialising SDK or when attempting to track an event?

**Comment by wangjunhua1** [comment]
just by initialising SDK and   track event

**Comment by uerceg** [comment]
Thanks for the info, we're checking this and will get back to you as soon as possible.

**Comment by wangjunhua1** [comment]
Thanks

**Comment by uerceg** [comment]
@wangjunhua1 

How are you adding our SDK to your app?

**Comment by wangjunhua1** [comment]
use  pod

**Comment by wangjunhua1** [comment]
Have you solved it ?

**Comment by popei69** [comment]
Hey guys, any update on that matter? I'm getting same issue and crash, mostly on iOS 13. Could it be related to api `[ADJUtil writeObject:fileName:objectName:]` being deprecated? Is there any plan to migrate to another one?

I'm tempted to temporarily disable the SDK altogether since it creates a lot more crash than it bring values to our users. Thanks

**Comment by uerceg** [comment]
We'll get back to investigation one more time, but it is pretty tricky without possibility to reproduce the issue. @popei69 this was reported even before iOS 13 was out and we still didn't have luck in any attempt to reproduce the issue and reporters of the issue either. Also, your point is correct, API archiving did get deprecated and migration to newly suggested method is planned to be added to most probably next iOS SDK update. But like said, is this going to be solution for the issue, still hard to say since even with deprecated code, our tests on iOS 13 devices didn't manage to reproduce the issue. Can you maybe reproduce the issue when running your app on iOS 13 device?

**Comment by popei69** [comment]
Hey @uerceg , so far I couldn't replicate it either. The error message `EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000` makes me think the item has been released by the time he's getting used or written by the archiver. 

Do you have an idea when when would be available the version migrating to the new `NSKeyedArchiver` api? I want to rule this out if it's part of the problem or not. Thanks

**Comment by uerceg** [comment]
@popei69 Thanks for follow up. We'll give our best to ship this update by end of next week.

**Comment by uerceg** [comment]
(copy-paste)

Hey guys. 

Thanks for patience on this one. We have just released an [update](https://github.com/adjust/ios_sdk/releases/tag/v4.21.0) where we have replaced deprecated API which might be the source of these issues. If you can please give it a shot and let us know if crashes are still there with latest version or not, would be great to hear.

Cheers

**Comment by popei69** [comment]
Hey @uerceg, thanks for the update, unfortunately I still have the same problem today, even with latest api used.

![image](https://user-images.githubusercontent.com/1432849/78330422-82f7d880-75b6-11ea-9fca-1d491480dbbf.png)

Is there any other way to investigate this one?

**Comment by uerceg** [comment]
@popei69 Hm, thanks for letting us know. Is the exception message same as in this [comment](https://github.com/adjust/ios_sdk/issues/350#issuecomment-583972794) of yours?

**Comment by popei69** [comment]
@uerceg Yeah similar as before, it's actually getting a bigger impact now on our users. I'm too sure how it got worse, but the stack trace seats at same place.

**Comment by uerceg** [comment]
Thanks for the info. We got few ideas on the road what we might do to hopefully try to address this, we will try to ship patch update next week. Still hard to say for us if it will truly fix the issue since regardless of attempts, we were still unable to reproduce the issue so far. Nevertheless, will keep you posted and thank you one more time for the feedback on the issue, really appreciated.

**Comment by uerceg** [comment]
@popei69 👋 

We have just released [v4.21.1 update](https://github.com/adjust/ios_sdk/releases/tag/v4.21.1) where we tried to address this issue with few more ideas. In case you manage to give it a shot and let us know if you're still seeing the same issue with this latest version or not, would be great.

Cheers

**Comment by uerceg** [comment]
And actually better to give [v4.21.2](https://github.com/adjust/ios_sdk/releases/tag/v4.21.2) a shot since one more thing is attempted in there on this topic.

**Comment by kantanta** [comment]
Reproduced on v4.21.2 

```
Crashed: io.adjust.PackageQueue
0  CoreFoundation                 0x1856362ac __CFBinaryPlistWriteOrPresize + 444
1  Foundation                     0x1859dc538 -[NSKeyedArchiver finishEncoding] + 528
2  Foundation                     0x1859dd6c4 -[NSKeyedArchiver encodedData] + 68
3  Foundation                     0x1859dcbb8 +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 128
4  Adjust                         0x10372a764 +[ADJUtil writeObject:fileName:objectName:] + 387 (ADJUtil.m:387)
5  Adjust                         0x10371f7cc -[ADJPackageHandler writePackageQueueS:] + 307 (ADJPackageHandler.m:307)
6  Adjust                         0x10371ee58 -[ADJPackageHandler addI:package:] + 214 (ADJPackageHandler.m:214)
7  Adjust                         0x10372f050 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 1241 (ADJUtil.m:1241)
8  libdispatch.dylib              0x1853de610 _dispatch_call_block_and_release + 24
9  libdispatch.dylib              0x1853df184 _dispatch_client_callout + 16
10 libdispatch.dylib              0x18538b404 _dispatch_lane_serial_drain$VARIANT$mp + 608
11 libdispatch.dylib              0x18538bdf8 _dispatch_lane_invoke$VARIANT$mp + 420
12 libdispatch.dylib              0x185395314 _dispatch_workloop_worker_thread + 588
13 libsystem_pthread.dylib        0x18542eb88 _pthread_wqthread + 276
14 libsystem_pthread.dylib        0x185431760 start_wqthread + 8
```

**Comment by uerceg** [comment]
Hi @kantanta 

Thanks for reporting. Do you by any chance use methods to set callback and/or partner parameters on `ADJEvent` object or maybe session callback and or partner parameters on `Adjust` instance in your app?

**Comment by kantanta** [comment]
Hi @uerceg 

Yes, we use:
`setRevenue`, `addCallbackParameter`, `addPartnerParameter` in `ADJEvent`
`trackAdRevenue`, `trackEvent` in `Adjust`

**Comment by uerceg** [comment]
Hi @kantanta 

And thanks for prompt response! Trying to investigate all weird potential scenarios. One more question - any of those string variables being passed is anywhere by any chance defined as mutable string?

**Comment by kantanta** [comment]
@uerceg 😁
No, all strings are immutable.

**Comment by uerceg** [comment]
@kantanta Thanks and can you please share the SDK initialisation and usage code and explain me where are you initialising SDK? Do you see this happening on app/SDK launch or later in the app while already running?

**Comment by uerceg** [comment]
👋 We have just released [v4.21.3](https://github.com/adjust/ios_sdk/releases/tag/v4.21.3) update where we tried to seal all theoretical attempts of mutation of objects which are being written to / read from package queue which seems to be the source of trouble for `NSKeyedArchiver` when performing encoding. Unfortunately, we were unable to reproduce this issue on our end and only way to see if issue is still there is again to give this version a shot and let us know if issue is still there.

Looking forward to hear from you and big thank you from our end on patience and willingness to work with us on trying to solve this one. 🙏

**Comment by kantanta** [comment]
Hi @uerceg 
I have bad news. It's still reproducing for some users with [v4.21.3](https://github.com/adjust/ios_sdk/releases/tag/v4.21.3) 

```
Crashed: io.adjust.PackageQueue
0  CoreFoundation                 0x196dff78c _CFArrayReplaceValues + 880
1  CoreFoundation                 0x196dfec0c CFArrayAppendValue + 148
2  CoreFoundation                 0x196e09cd0 _flattenPlist + 272
3  CoreFoundation                 0x196e09e74 _flattenPlist + 692
4  CoreFoundation                 0x196e09e0c _flattenPlist + 588
5  CoreFoundation                 0x196e09e74 _flattenPlist + 692
6  CoreFoundation                 0x196e09e0c _flattenPlist + 588
7  CoreFoundation                 0x196e098d4 __CFBinaryPlistWriteOrPresize + 232
8  Foundation                     0x1971b27d0 -[NSKeyedArchiver finishEncoding] + 528
9  Foundation                     0x1971b3950 -[NSKeyedArchiver encodedData] + 68
10 Foundation                     0x1971b2e44 +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 120
11 Adjust                         0x105a0235c +[ADJUtil writeObject:fileName:objectName:] + 387 (ADJUtil.m:387)
12 Adjust                         0x1059f6c80 -[ADJPackageHandler writePackageQueueS:] + 307 (ADJPackageHandler.m:307)
13 Adjust                         0x1059f65dc -[ADJPackageHandler sendNextI:] + 249 (ADJPackageHandler.m:249)
14 Adjust                         0x105a06c48 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 1241 (ADJUtil.m:1241)
15 libdispatch.dylib              0x196baa9a8 _dispatch_call_block_and_release + 24
16 libdispatch.dylib              0x196bab524 _dispatch_client_callout + 16
17 libdispatch.dylib              0x196b578a4 _dispatch_lane_serial_drain$VARIANT$mp + 608
18 libdispatch.dylib              0x196b58294 _dispatch_lane_invoke$VARIANT$mp + 416
19 libdispatch.dylib              0x196b6178c _dispatch_workloop_worker_thread + 588
20 libsystem_pthread.dylib        0x196bfcb74 _pthread_wqthread + 272
21 libsystem_pthread.dylib        0x196bff740 start_wqthread + 8
```

**Comment by uerceg** [comment]
HI @kantanta 

Thanks for the report and indeed, quite annoying issue it seems. What I'm curious about is do you have any information on users of these devices which are experiencing this issue in terms of which version of your app did they use before updating to this current one where you're seeing these logs? I guess what I'm trying to find out is if this is specific to users which updated to certain newer SDK version from some pretty old one (which you may had in some of your previous app versions) or does this happen even for devices which were updating your app in last few versions (so pretty much meaning happens for someone who updated from SDK v4.21.2 to v4.21.3)?

Also do you see this happening only once per device or do you see same issue happening multiple time on same device (not sure if this metric is available)?

**Comment by kantanta** [comment]
@uerceg, in the last 7 days we had ~150 crashes for 20 users, some of them had this issue more than 20 times. I will give you more info about SDK versions in few days.

**Comment by uerceg** [comment]
Thanks! And if you can share what ever you might find in common for these 20 devices (or any info about them if nothing really in common) - device type, which iOS version, would be great.

**Comment by kantanta** [comment]
Hi @uerceg 
This is some information about users who has experienced this crash.
Also I noticed that all crashes had happened when the user had low RAM free ~50MB 
One user could have several version of Adjust SDK.

```
user1, 13.1.3, iPhone7Plus, Adjust 4.18.3
user1, 13.3, iPhone7Plus, Adjust 4.18.3
user1, 13.3.1, iPhone7Plus, Adjust 4.18.3
user1, 13.3.1, iPhone7Plus, Adjust 4.20.0
user2, 13.3.1, iPhone7Plus, Adjust 4.20.0
user3, 12.4, iPhone7Plus, Adjust 4.18.0
user3, 12.4.1, iPhone7Plus, Adjust 4.18.0
user3, 13.1.1, iPhone7Plus, Adjust 4.18.0
user3, 13.1.1, iPhone7Plus, Adjust 4.18.3
user3, 13.1.2, iPhone7Plus, Adjust 4.18.3
user3, 13.1.3, iPhone7Plus, Adjust 4.18.3
user3, 13.2.2, iPhone7Plus, Adjust 4.18.3
user3, 13.2.3, iPhone7Plus, Adjust 4.18.3
user3, 13.3, iPhone7Plus, Adjust 4.18.3
user3, 13.3.1, iPhone7Plus, Adjust 4.18.3
user3, 13.3.1, iPhone7Plus, Adjust 4.20.0
user4, 13.3.1, iPhone7Plus, Adjust 4.18.3
user4, 13.3.1, iPhone7Plus, Adjust 4.20.0
user4, 13.3.1, iPhone7Plus, Adjust 4.21.0
user4, 13.3.1, iPhone7Plus, Adjust 4.21.1
user4, 13.3.1, iPhone7Plus, Adjust 4.21.2
user4, 12.3.1, "iPhone9,4", Adjust 4.17.3
user4, 12.3.1, iPhone7Plus, Adjust 4.18.0
user4, 12.4.1, iPhone7Plus, Adjust 4.18.0
user4, 12.4.1, iPhone7Plus, Adjust 4.18.3
user4, 13.3, iPhone7Plus, Adjust 4.18.3
user5, 13.3, iPhone8Plus, Adjust 4.18.3
user5, 13.3.1, iPhone8Plus, Adjust 4.18.3
user5, 13.3.1, iPhone8Plus, Adjust 4.20.0
user6, 13.3.1,iPhone7Plus, Adjust 4.18.3
user6, 13.3.1, iPhone7Plus, Adjust 4.20.0
```

**Comment by uerceg** [comment]
Hi @kantanta 

Thanks for this info. Are all these users today on v4.21.3 and have experienced crash with v4.21.3? Are these versions you wrote the ones they updated to v4.21.3 from?

**Comment by kantanta** [comment]
@uerceg yes, all these users have 4.21.3 now. I guess it needs some explanation for this info 😁 Look at the user1, hi had several sdk versions and came to 4.21.3 from 4.20.0, user4 came from 4.21.2.

**Comment by popei69** [comment]
Just to follow up, I have also tried to update to latest SDK to 4.21.3 and got way more crash that before, exactly the same as when I did updated to 4.21.0 couple months back. That's the second time I have to roll back to another previous version that seems somehow more stable (or less crashes happen).

Regarding the impact, I've got the same informations as above: only iOS13 from different type of iPhones. Let me know if you have any advise or update on this. Thanks!

**Comment by uerceg** [comment]
Hi @popei69 and @kantanta 👋 

Even with all the information provided by @kantanta (many thanks for that), we were absolutely unable to reproduce any of these issues on our end. It is pretty annoying to try to address an issue without ability to reproduce it, but we continued to work in order to address this issue and are at the moment refactoring few parts of the SDK which in theory might be responsible for these occasional crashes. We'll have this live in our next iOS SDK release and hopefully be able to address this issue with those changes.

Will keep you posted on this one and thank you one more time for all the input and patience!

Cheers

**Comment by uerceg** [comment]
Hey guys,

Today we released [v4.22.0](https://github.com/adjust/ios_sdk/releases/tag/v4.22.0) update where we tried to address this issue with some other approach (but like in previous attempts, quite hard without possibility to reproduce the issue).

Nevertheless, if you are able to give it a shot, feel free to and looking forward to hear back from you.

Cheers

**Comment by kantanta** [comment]
Hi @uerceg 

It's still reproducing with [v4.22.1](https://github.com/adjust/ios_sdk/releases/tag/v4.22.1) 

```
Crashed: io.adjust.PackageQueue
0  CoreFoundation                 0x19dde9a40 __CFBinaryPlistWriteOrPresize + 488
1  Foundation                     0x19e192c20 -[NSKeyedArchiver finishEncoding] + 528
2  Foundation                     0x19e193da0 -[NSKeyedArchiver encodedData] + 68
3  Foundation                     0x19e193294 +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 120
4  Adjust                         0x106523e50 +[ADJUtil writeObject:fileName:objectName:syncObject:] + 334 (ADJUtil.m:334)
5  Adjust                         0x106515e84 __40-[ADJPackageHandler writePackageQueueS:]_block_invoke + 341 (ADJPackageHandler.m:341)
6  Adjust                         0x10652659c +[ADJUtil launchSynchronisedWithObject:block:] + 790 (ADJUtil.m:790)
7  Adjust                         0x106515df4 -[ADJPackageHandler writePackageQueueS:] + 346 (ADJPackageHandler.m:346)
8  Adjust                         0x106515054 -[ADJPackageHandler addI:package:] + 223 (ADJPackageHandler.m:223)
9  Adjust                         0x1065264e4 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 783 (ADJUtil.m:783)
10 libdispatch.dylib              0x19db8a9a8 _dispatch_call_block_and_release + 24
11 libdispatch.dylib              0x19db8b524 _dispatch_client_callout + 16
12 libdispatch.dylib              0x19db68b3c _dispatch_lane_serial_drain$VARIANT$armv81 + 564
13 libdispatch.dylib              0x19db6954c _dispatch_lane_invoke$VARIANT$armv81 + 396
14 libdispatch.dylib              0x19db7284c _dispatch_workloop_worker_thread + 580
15 libsystem_pthread.dylib        0x19dbdcb74 _pthread_wqthread + 272
16 libsystem_pthread.dylib        0x19dbdf740 start_wqthread + 8
```

**Comment by ShingoFukuyama** [comment]
We got a crash on v4.23.1, iPhone XR, iOS 14.0.1, very rarely occurs though

Crashed: io.adjust.PackageQueue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

```
Crashed: io.adjust.PackageQueue
0  CoreFoundation                 0x18e201700 _CFArrayReplaceValues + 840
1  CoreFoundation                 0x18e200c0c CFArrayAppendValue + 168
2  CoreFoundation                 0x18e20d9cc _flattenPlist + 280
3  CoreFoundation                 0x18e20db78 _flattenPlist + 708
4  CoreFoundation                 0x18e20db10 _flattenPlist + 604
5  CoreFoundation                 0x18e20d5c8 __CFBinaryPlistWriteOrPresize + 236
6  Foundation                     0x18f4f44e4 -[NSKeyedArchiver finishEncoding] + 548
7  Foundation                     0x18f4f5724 -[NSKeyedArchiver encodedData] + 76
8  Foundation                     0x18f4f4b84 +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 124
9  Adjust                         0x1020dbb40 +[ADJUtil writeObject:fileName:objectName:syncObject:] + 284
10 Adjust                         0x1020cc7f8 __40-[ADJPackageHandler writePackageQueueS:]_block_invoke + 108
11 Adjust                         0x1020de288 +[ADJUtil launchSynchronisedWithObject:block:] + 72
12 Adjust                         0x1020cc768 -[ADJPackageHandler writePackageQueueS:] + 176
13 Adjust                         0x1020cb9cc -[ADJPackageHandler addI:package:] + 420
14 Adjust                         0x1020de1d0 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 48
15 libdispatch.dylib              0x18deeafd0 _dispatch_call_block_and_release + 32
16 libdispatch.dylib              0x18deecac8 _dispatch_client_callout + 20
17 libdispatch.dylib              0x18def3c08 _dispatch_lane_serial_drain + 580
18 libdispatch.dylib              0x18def4734 _dispatch_lane_invoke + 408
19 libdispatch.dylib              0x18defe528 _dispatch_workloop_worker_thread + 708
20 libsystem_pthread.dylib        0x1d5848908 _pthread_wqthread + 276
21 libsystem_pthread.dylib        0x1d584f77c start_wqthread + 8
```

**Comment by uerceg** [comment]
Hi guys,

Can you please give [latest iOS SDK v4.33.4 update](https://github.com/adjust/ios_sdk/releases/tag/v4.33.4) a shot and let us know if this issue still appears with that version? We have gotten confirmation from one client that changes we introduced in this SDK update (and which client tried prior to this release) caused their app not to see crashes with this same stack trace anymore. Looking forward to hear back from you on this one.

**Comment by uerceg** [comment]
I'll close this issue for now, but in case you still end up seeing this issue with iOS SDK v4.33.4 or later, please feel free to comment / reopen. Cheers.
