### ISSUE TITLE
Crash: NSDictionary mutated while being enumerated in [ADJUtil sendPostRequest:....]

### ISSUE THREAD

**Issue by fonesti** [adjust/ios_sdk#387]
We are receiving crash reports with crash at `[ADJUtil sendPostRequest:queueSize:prefixErrorMessage:suffixErrorMessage:activityPackage:responseDataHandler:]`.

- Adjust version: `4.17.3`
- More than 600 unique devices affected
- **Time from launch is always < 4s**, usually around 2s

```
NSGenericExceptionADJUtil.m:515 
*** Collection <__NSDictionaryM: 0x280530580> was mutated while being enumerated.
```

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  11

Exception backtrace 
0   CoreFoundation                	0x1c297e98c __exceptionPreprocess + 228 (NSException.m:172)
1   libobjc.A.dylib               	0x1c1b579f8 objc_exception_throw + 56 (objc-exception.mm:557)
2   CoreFoundation                	0x1c297e254 __NSFastEnumerationMutationHandler + 128 (NSEnumerator.m:133)
3   CoreFoundation                	0x1c287596c -[NSMutableDictionary addEntriesFromDictionary:] + 260 (NSMutableDictionary.m:30)
4   Adjust                        	0x104a28634 +[ADJUtil sendPostRequest:queueSize:prefixErrorMessage:suffixErrorMessage:activityPackage:responseDataHandler:] + 181812 (ADJUtil.m:515)
5   Adjust                        	0x104a1d594 -[ADJRequestHandler sendI:activityPackage:queueSize:] + 136596 (ADJRequestHandler.m:101)
6   Adjust                        	0x104a2ba40 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke + 195136 (ADJUtil.m:1141)
7   libdispatch.dylib             	0x1c23bca38 _dispatch_call_block_and_release + 24 (init.c:1372)
8   libdispatch.dylib             	0x1c23bd7d4 _dispatch_client_callout + 16 (object.m:511)
9   libdispatch.dylib             	0x1c2366324 _dispatch_lane_serial_drain$VARIANT$mp + 592 (inline_internal.h:2441)
10  libdispatch.dylib             	0x1c2366e40 _dispatch_lane_invoke$VARIANT$mp + 428 (queue.c:3805)
11  libdispatch.dylib             	0x1c236f4ac _dispatch_workloop_worker_thread + 596 (queue.c:5889)
12  libsystem_pthread.dylib       	0x1c259e114 _pthread_wqthread + 304 (pthread.c:2371)
13  libsystem_pthread.dylib       	0x1c25a0cd4 start_wqthread + 4
```

**Comment by uerceg** [comment]
Hi @fonesti

Thanks for reporting. We'll investigate and keep you posted.

Any pattern maybe in OS version of affected devices or is it pretty random?

**Comment by fonesti** [comment]
> Hi @fonesti
> 
> Thanks for reporting. We'll investigate and keep you posted.
> 
> Any pattern maybe in OS version of affected devices or is it pretty random?

**Comment by uerceg** [comment]
Thanks for letting us know. In case we have any follow up questions, we'll ping you in here.

**Comment by fonesti** [comment]
@uerceg More details from another crash reporting tool
The stack trace is the one posted above.
 
```
NSGenericExceptionADJUtil.m:515 *** Collection <__NSDictionaryM: 0x280530580> was mutated while being enumerated.
```

**Comment by uerceg** [comment]
Hi @fonesti 

We have just released [v4.21.3](https://github.com/adjust/ios_sdk/releases/tag/v4.21.3) update where we tried to seal all theoretical attempts of mutation of objects which might be responsible for this crash as well.

In case you can give this version a shot and let us know if you're maybe still seeing this crash with it, would be great.

Cheers

**Comment by fonesti** [comment]
Great 👏  We should be able to gather some data about it within a month! I'll keep you posted.

**Comment by fonesti** [comment]
@uerceg  Unfortunately is still happening at app launch with `4.21.3` (~200 events/day)

Here some richer info (crashing thread + another thread with frames in Adjust).
Is this kind of concurrent activity expected?
Let me know should you need other info 🙌 

```
NSGenericException: *** Collection <__NSDictionaryM: 0x2823679a0> was mutated while being enumerated.

Thread 31
0  CoreFoundation          ___exceptionPreprocess
1  libobjc.A.dylib         _objc_exception_throw
2  CoreFoundation          ___NSFastEnumerationMutationHandler
3  CoreFoundation          -[NSMutableDictionary addEntriesFromDictionary:]
4  _MyApp                  +[ADJUtil sendPostRequest:queueSize:prefixErrorMessage:suffixErrorMessage:activityPackage:responseDataHandler:] (ADJUtil.m:565:5)
5  _MyApp                  -[ADJRequestHandler sendI:activityPackage:queueSize:] (ADJRequestHandler.m:101:5)
6  _MyApp                  __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke (ADJUtil.m:1240:9)
7  libdispatch.dylib       __dispatch_call_block_and_release
8  libdispatch.dylib       __dispatch_client_callout
9  libdispatch.dylib       __dispatch_lane_serial_drain$VARIANT$mp
10 libdispatch.dylib       __dispatch_lane_invoke$VARIANT$mp
11 libdispatch.dylib       __dispatch_workloop_worker_thread
12 libsystem_pthread.dylib __pthread_wqthread
13 libsystem_pthread.dylib _start_wqthread

Thread 32
0  CoreFoundation          __CFRelease
1  Foundation              -[NSKeyedArchiver dealloc]
2  Foundation              -[NSKeyedArchiver dealloc]
3  Foundation              +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:]
4  _MyApp                  +[ADJUtil writeObject:fileName:objectName:] (ADJUtil.m:387:32)
5  _MyApp                  -[ADJPackageHandler writePackageQueueS:] (ADJPackageHandler.m:307:9)
6  _MyApp                  -[ADJPackageHandler updatePackagesI:sessionParameters:] (ADJPackageHandler.m:280:5)
7  _MyApp                  __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke (ADJUtil.m:1240:9)
8  libdispatch.dylib       __dispatch_call_block_and_release
9  libdispatch.dylib       __dispatch_client_callout
10 libdispatch.dylib       __dispatch_lane_serial_drain$VARIANT$mp
11 libdispatch.dylib       __dispatch_lane_invoke$VARIANT$mp
12 libdispatch.dylib       __dispatch_workloop_worker_thread
13 libsystem_pthread.dylib __pthread_wqthread
```

**Comment by uerceg** [comment]
(copy/paste)

Hey guys,

Today we released [v4.22.0](https://github.com/adjust/ios_sdk/releases/tag/v4.22.0) update where we tried to address this issue with some other approach (but like in previous attempts, quite hard without possibility to reproduce the issue).

Nevertheless, if you are able to give it a shot, feel free to and looking forward to hear back from you.

Cheers

**Comment by uerceg** [comment]
In case this particular issue ends up being present in latest iOS SDK version, feel free to comment/reopen. Cheers.
